### ISSUE TITLE
Richiesta funzionalità per LXClient

### ISSUE THREAD

**Issue by giuliotoplad** [xMarkz/LXClient#2]
Salve volevo sapere se nella prossima Release per voi era possibile aggiungere la possibilità di mettere il Client a schermo intero, chiedo ciò perché ho un portatile piccolo a bassa risoluzione e prima della fine di Flash mi tornava molto comodo mettere la finestra a schermo intero.
Fatemi sapere, grazie.

**Comment by xMarkz** [comment]
La funzionalità sarà disponibile dal prossimo rilascio del launcher.
